### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by hkvstore** [sebaferreras/Ionic3-MultiLevelSideMenu#37]
I'd like to suggest changing the CSS as follows so it will not affect other ion-items in the app:

```css
// ------------------------------------ //
// Simple items                         //
// ------------------------------------ //
side-menu-content {
    ion-item.item-ios,
    ion-item.item-md,
    ion-item.item-wp {

        padding-left: 16px;
        padding-right: 16px;
        min-height: 50px;

        &.item.item-block {
            border-bottom: 1px solid $item-color-bg;
        }
        
        & [item-left], 
        & [item-right] {
            margin-left: 0;
        }

        & ion-icon[item-left] + .item-inner, 
        & ion-icon[item-left] + .item-input {
        margin-left: 8px;
        }
    }
}
```
